# Generated by Django 3.1.7 on 2021-03-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('Alcohol and Hygiene', 'Alcohol and Hygiene'), ('Candy/Gum', 'Candy/Gum'), ('Canned Drinks/Bottled Drinks/Powdered Drinks', 'Canned Drinks/Bottled Drinks/Powdered Drinks'), ('Gong Cha', 'Gong Cha'), ('Magazines', 'Magazines'), ('Pastries', 'Pastries'), ('Potato Corner', 'Potato Corner'), ('Snacks', 'Snacks'), ('Turks', 'Turks')], max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
