# Generated by Django 3.1.7 on 2021-03-23 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashier', '0003_auto_20210302_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=70)),
                ('barangay', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=4)),
                ('home_phone', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Alcohol and Hygiene', 'Alcohol and Hygiene'), ('Candy/Gum', 'Candy/Gum'), ('Canned Drinks/Bottled Drinks/Powdered Drinks', 'Canned Drinks/Bottled Drinks/Powdered Drinks'), ('Gong Cha', 'Gong Cha'), ('Magazines', 'Magazines'), ('Pastries', 'Pastries'), ('Potato Corner', 'Potato Corner'), ('Snacks', 'Snacks'), ('Turks', 'Turks')], max_length=44)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('mobile_phone', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('mobile_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('receive_date', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('GCash', 'GCash'), ('Cash On Delivery', 'Cash On Delivery'), ('Cash On Pickup', 'Cash On Pickup')], max_length=20)),
                ('order_status', models.CharField(choices=[('Order Sent', 'Order Sent'), ('Order Confirmed', 'Order Confirmed'), ('Payment Sent', 'Payment Sent'), ('Payment Confirmed', 'Payment Confirmed'), ('Ready for Pickup', 'Ready for Pickup'), ('To Be Delivered', 'To Be Delivered'), ('Order On The Way', 'Order On The Way'), ('Delivered', 'Delivered')], max_length=20)),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='')),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.address')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.cashier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.driver')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.order')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.order')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.customer'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.category'),
        ),
    ]
