# Generated by Django 3.1.7 on 2021-04-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0008_orderstatus_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
