# Generated by Django 3.1.7 on 2021-04-02 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0010_auto_20210403_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recieve_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.orderstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_date',
            field=models.DateField(null=True),
        ),
    ]
