# Generated by Django 3.1.7 on 2021-04-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0011_auto_20210403_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cashier',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(default='Order Sent', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.orderstatus'),
        ),
        migrations.DeleteModel(
            name='Cashier',
        ),
    ]
