# Generated by Django 3.1.7 on 2021-04-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0012_auto_20210403_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashier.orderstatus'),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
