# Generated by Django 3.1.7 on 2021-04-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0013_auto_20210409_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='recieve_time',
            new_name='receive_time',
        ),
    ]
